[application]

# App icon
icon = ["assets/icons/icon.ico"]

[web.app]

# HTML title tag content
title = "Panduza Serial Port"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["assets/serial-display.css"]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
